# Generated by Django 4.2.3 on 2025-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='experiencePoints',
            field=models.IntegerField(default=0, help_text="User's experience points"),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lastWorked',
            field=models.DateTimeField(blank=True, help_text='Last time the user worked', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='level',
            field=models.IntegerField(default=1, help_text="User's level"),
        ),
        migrations.AddField(
            model_name='userdata',
            name='maxStreak',
            field=models.IntegerField(default=0, help_text='Maximum streak of consecutive days working'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='streak',
            field=models.IntegerField(default=0, help_text='Current streak of consecutive days working'),
        ),
    ]
