# Generated by Django 4.2.3 on 2025-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata_experiencepoints_userdata_lastworked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dailyGoal',
            field=models.IntegerField(default=0, help_text='Daily goal in minutes, 0 means no goal'),
        ),
    ]
