# Generated by Django 4.2.3 on 2025-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdata_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='countUp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='font',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='wallpaper',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
