# Generated by Django 4.2.3 on 2025-06-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdata_countup_userdata_font_userdata_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='accentColor',
            field=models.CharField(default='pink', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='darkMode',
            field=models.BooleanField(default=True),
        ),
    ]
