# Generated by Django 4.2.3 on 2025-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdata_dailygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='isNeighborhood',
            field=models.BooleanField(default=False, help_text='Whether the user is part of the HackClub Neighborhood'),
        ),
    ]
