# Generated by Django 4.2.3 on 2025-06-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdata_accentcolor_userdata_darkmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='countUp',
        ),
        migrations.AddField(
            model_name='userdata',
            name='isOnline',
            field=models.BooleanField(default=True),
        ),
    ]
