# Generated by Django 4.2.3 on 2025-06-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userdata_countup_userdata_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='backgroundBlur',
            field=models.BooleanField(default=False, help_text='Enable background blur'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='breakReminders',
            field=models.BooleanField(default=True, help_text='Enable break reminders'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='desktopNotifications',
            field=models.BooleanField(default=True, help_text='Enable desktop notifications'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='focusDuration',
            field=models.IntegerField(default=25, help_text='Focus duration in minutes'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='longBreakDuration',
            field=models.IntegerField(default=15, help_text='Long break duration in minutes'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='longBreakInterval',
            field=models.IntegerField(default=4, help_text='Number of pomodoros before a long break'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='pauseIsBreak',
            field=models.BooleanField(default=True, help_text='Whether to treat pause as a break'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='playSoundOnNotification',
            field=models.BooleanField(default=True, help_text='Play sound on notification'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profilePhoto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='shortBreakDuration',
            field=models.IntegerField(default=5, help_text='Short break duration in minutes'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='showOnlineStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='showTimeSpendStudying',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='standUpReminders',
            field=models.BooleanField(default=True, help_text='Enable stand up reminders'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='accentColor',
            field=models.CharField(default='#10b981', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='wallpaper',
            field=models.CharField(default='leaves.jpg', max_length=255),
        ),
    ]
