# Generated by Django 4.2.3 on 2025-06-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdata_friends_userdata_timezone_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the onboarding process'),
        ),
    ]
