# Generated by Django 5.2.3 on 2025-06-25 09:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('pomodoro', 'Pomodoro'), ('free', 'Free')], default='pomodoro', max_length=50, null=True)),
                ('phase', models.CharField(blank=True, choices=[('focus', 'Focus'), ('shortBreak', 'Short Break'), ('longBreak', 'Long Break'), ('free', 'Free'), ('paused', 'Paused')], max_length=50, null=True)),
                ('pomodoroCount', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('isConnected', models.BooleanField(default=True)),
                ('lastDisconnected', models.DateTimeField(blank=True, help_text='Timestamp when the session was last disconnected.', null=True)),
                ('lastBreakStartTime', models.DateTimeField(blank=True, help_text='Timestamp when the session was last Break-ed.', null=True)),
                ('accumulatedBreakDuration', models.DurationField(default=datetime.timedelta(0), help_text='Total accumulated duration of all breaks for this session.')),
                ('lastPauseStartTime', models.DateTimeField(blank=True, help_text='Timestamp when the session was last paused.', null=True)),
                ('accumulatedPauseDuration', models.DurationField(default=datetime.timedelta(0), help_text='Total accumulated duration of all pauses for this session.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('totalTime', models.DurationField()),
                ('activeTime', models.DurationField(blank=True, null=True)),
                ('breakTime', models.DurationField()),
                ('pauseTime', models.DurationField()),
                ('startTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomo_session_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
