# Generated by Django 4.2.3 on 2025-06-01 10:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(blank=True, max_length=100, unique=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('isRunning', models.BooleanField(default=True)),
                ('totalTime', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('activeTime', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('last_pause_start_time', models.DateTimeField(blank=True, help_text='Timestamp when the session was last paused.', null=True)),
                ('accumulated_pause_duration', models.DurationField(default=datetime.timedelta(0), help_text='Total accumulated duration of all pauses for this session.')),
                ('users', models.ManyToManyField(related_name='pomo_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
