# Generated by Django 4.2.3 on 2025-06-04 04:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pomo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomosession',
            name='activeTime',
        ),
        migrations.RemoveField(
            model_name='pomosession',
            name='sessionId',
        ),
        migrations.RemoveField(
            model_name='pomosession',
            name='totalTime',
        ),
        migrations.RemoveField(
            model_name='pomosession',
            name='users',
        ),
        migrations.AddField(
            model_name='pomosession',
            name='anonymousId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pomosession',
            name='isConnected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomosession',
            name='lastDisconnected',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the session was last disconnected.', null=True),
        ),
        migrations.AddField(
            model_name='pomosession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomo_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pomosession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PomoSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('totalTime', models.DurationField(default=datetime.timedelta(0))),
                ('activeTime', models.DurationField(default=datetime.timedelta(0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomo_session_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(blank=True, max_length=100, unique=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('isRunning', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='group_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
