# Generated by Django 4.2.3 on 2025-06-06 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0002_remove_pomosession_activetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomosessiondata',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 8, 51, 46, 146180, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
