# Generated by Django 4.2.3 on 2025-06-12 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pomo', '0003_pomosessiondata_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('pomodoro', 'Pomodoro'), ('free', 'Free')], default='pomodoro', max_length=50, null=True)),
                ('phase', models.CharField(choices=[('focus', 'Focus'), ('shortBreak', 'Short Break'), ('longBreak', 'Long Break'), ('free', 'Free'), ('paused', 'Paused')], default='work', max_length=50)),
                ('pomodoroCount', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('isConnected', models.BooleanField(default=True)),
                ('lastDisconnected', models.DateTimeField(blank=True, help_text='Timestamp when the session was last disconnected.', null=True)),
                ('lastBreakStartTime', models.DateTimeField(blank=True, help_text='Timestamp when the session was last Break-ed.', null=True)),
                ('accumulatedBreakDuration', models.DurationField(default=datetime.timedelta(0), help_text='Total accumulated duration of all breaks for this session.')),
                ('lastPauseStartTime', models.DateTimeField(blank=True, help_text='Timestamp when the session was last paused.', null=True)),
                ('accumulatedPauseDuration', models.DurationField(default=datetime.timedelta(0), help_text='Total accumulated duration of all pauses for this session.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('totalTime', models.DurationField()),
                ('activeTime', models.DurationField(blank=True, null=True)),
                ('breakTime', models.DurationField()),
                ('startTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomo_session_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pomosession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pomosessiondata',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupSession',
        ),
        migrations.DeleteModel(
            name='PomoSession',
        ),
        migrations.DeleteModel(
            name='PomoSessionData',
        ),
    ]
