# Generated by Django 4.2.3 on 2025-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0004_currentsession_sessiondata_remove_pomosession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsession',
            name='phase',
            field=models.CharField(blank=True, choices=[('focus', 'Focus'), ('shortBreak', 'Short Break'), ('longBreak', 'Long Break'), ('free', 'Free'), ('paused', 'Paused')], max_length=50, null=True),
        ),
    ]
