# Generated by Django 4.2.3 on 2025-06-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0005_alter_currentsession_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentsession',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RemoveField(
            model_name='currentsession',
            name='end_time',
        ),
    ]
