# Generated by Django 4.2.3 on 2025-06-13 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0006_rename_start_time_currentsession_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='pauseTime',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
